[ENG-237] - Provide Diff Log with NetBox
orb-community/diode pull request #112
Opened 2023-05-25 21:29 UTC by brnvalenca

2023-05-26 16:23 UTC, lpegoraro commented on .gitignore
> +docker/config.yml
Add a config to your editor to always put a empty line at the end of the file, 

 > An empty line at the end of a file may not be strictly necessary, but it is often recommended in coding practices. Some text editors, including Visual Studio Code, even automatically add an empty line to the end of a file when it is saved. Here are a few reasons why an empty line at the end of a file can be beneficial:
 >  It prevents issues with some command-line tools that expect a file to end in a newline character. 2. It makes it clear where the file ends, which can aid in readability and parsing.
 >  It can prevent trailing whitespace from causing unintended issues in some cases.
 >  It is recommended by some style guides, such as the Google Style Guide.
 > Overall, while it may not be strictly required in all cases, adding an empty line at the end of a file can be a good practice to follow.
 
 https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

2023-05-26 16:24 UTC, lpegoraro commented on cmd/service/main.go
> +
another VS Code config, don't leave trailing spaces.

2023-05-26 16:27 UTC, lpegoraro commented on service/service.go
> +
another VS Config, use the gofmt at the Save File, so these trailing spaces and lines are removed.

2023-05-26 16:32 UTC, lpegoraro commented on service/translate/types.go
> +			sb.WriteString(string(sqJson) + "\n")
These would be too verbose, I think it should only have the diffs

2023-05-26 16:38 UTC, lpegoraro commented on service/translate/types.go
> +			}
I would prefer it to be like a json, showing the differences for each field 
```json
{ "device_diffs" : [
  {
    
    "name" : {
      "suzieQ": "value1",
      "netbox": "value2"
    },
    "model" : {
      "suzieQ": "value1",
      "netbox": "value2"
    }
  }
]}
```

2023-05-26 17:05 UTC, brnvalenca commented on service/translate/types.go
> +			sb.WriteString(string(sqJson) + "\n")
okay, its going to be done. thanks!

2023-05-26 17:05 UTC, brnvalenca commented on service/translate/types.go
> +			}
i will do that, thanks!

2023-05-31 19:39 UTC, lpegoraro requested changes
a few more comments

2023-05-31 19:39 UTC, lpegoraro commented on service/translate/translate.go
> +				fmt.Println(ret)
we should use the zap logger instead of the fmt.Println.

2023-05-31 19:39 UTC, lpegoraro commented on service/translate/translate.go
> +				fmt.Println(ret)
we should use the zap logger instead of the fmt.Println.

2023-05-31 19:39 UTC, lpegoraro commented on service/translate/translate.go
> +				fmt.Println(ret)
```suggestion
                                 st.logger.Info("devices difference", zap.String("diffs": ret));
 ```

2023-05-31 19:39 UTC, lpegoraro commented on cmd/service/main.go
> +
this is still here.

2023-05-31 19:55 UTC, lpegoraro approved these changes
LGTM

2023-05-31 20:27 UTC, merged